{
	"schema_version": "1.6.0",
	"id": "RLSA-2020:3185",
	"modified": "2023-02-02T14:10:03.154035Z",
	"published": "2020-07-28T13:17:06Z",
	"related": [
		"CVE-2020-11538",
		"CVE-2020-5313"
	],
	"summary": "Important: python-pillow security update",
	"details": "The python-pillow packages contain a Python image processing library that provides extensive file format support, an efficient internal representation, and powerful image-processing capabilities.\n\nSecurity Fix(es):\n\n* python-pillow: out-of-bounds reads/writes in the parsing of SGI image files in expandrow/expandrow2 (CVE-2020-11538)\n\n* python-pillow: out-of-bounds read in ImagingFliDecode when loading FLI images (CVE-2020-5313)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Rocky Linux:8",
				"name": "python-pillow",
				"purl": "pkg:rpm/rocky-linux/python-pillow?distro=rocky-linux-8-4-legacy&epoch=0"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:5.1.1-12.el8_2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/resf-osv-data/RLSA-2020:3185.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://errata.rockylinux.org/RLSA-2020:3185"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1789532"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1852814"
		}
	],
	"credits": [
		{
			"name": "Rocky Enterprise Software Foundation"
		},
		{
			"name": "Red Hat"
		}
	]
}
